
export const phoneCodes = [
  { country: 'India', code: '+91' },
  { country: 'United States', code: '+1' },
  { country: 'United Kingdom', code: '+44' },
  { country: 'Australia', code: '+61' },
  { country: 'Canada', code: '+1' },
  { country: 'China', code: '+86' },
  { country: 'France', code: '+33' },
  { country: 'Germany', code: '+49' },
  { country: 'Japan', code: '+81' },
  { country: 'Russia', code: '+7' },
  { country: 'Singapore', code: '+65' },
  { country: 'South Africa', code: '+27' },
  { country: 'South Korea', code: '+82' },
  { country: 'Spain', code: '+34' },
  { country: 'Brazil', code: '+55' },
  { country: 'Mexico', code: '+52' },
  { country: 'Indonesia', code: '+62' },
  { country: 'Pakistan', code: '+92' },
  { country: 'Nigeria', code: '+234' },
  { country: 'Bangladesh', code: '+880' },
  { country: 'United Arab Emirates', code: '+971' },
  { country: 'Saudi Arabia', code: '+966' },
];
