// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eibwgihhvifnydslfztm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpYndnaWhodmlmbnlkc2xmenRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDgwMDMsImV4cCI6MjA1ODM4NDAwM30.XBJ4XQO_eFtn_3wbaH7dTjB-XRncLLaD5DPAG0mCFQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);